### ISSUE TITLE
Node 8.x.x doesn't work

### ISSUE THREAD

**Issue by dolanmiu** [Kitt-AI/snowboy#212]
Need prebuilt binaries for node `8.x.x`. Similar to this ticket:

https://github.com/Kitt-AI/snowboy/issues/117

```
node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
```

**Comment by chenguoguo** [comment]
We'll include it in the next release. For now you can build from our github repository.

**Comment by jaumard** [comment]
npm try to build from source when it doesn't find a prebuilt binary, but it fail too

Full log: 

```
snowboy@1.2.0 install /home/travis/build/mylisabox/lisa-box/node_modules/snowboy
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/snowboy.node] Error 1
make: Leaving directory `/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v8.0.0/bin/node" "/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64"
gyp ERR! cwd /home/travis/build/mylisabox/lisa-box/node_modules/snowboy
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v8.0.0/bin/node /home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Linux 4.8.12-040812-generic
node-pre-gyp ERR! command "/home/travis/.nvm/versions/node/v8.0.0/bin/node" "/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/mylisabox/lisa-box/node_modules/snowboy
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/versions/node/v8.0.0/bin/node /home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/travis/build/mylisabox/lisa-box/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-06-04T07_46_50_668Z-debug.log
```

**Comment by evancohen** [comment]
You need to install build dependencies. From the README:
```
sudo apt-get install libmagic-dev libatlas-base
```

**Comment by chenguoguo** [comment]
Closing this since installing `libmagic-dev` and `libatlas-base` should have fixed the problem.

**Comment by aluxian** [comment]
This worked for me on Raspberry Pi (ARM):

```
sudo apt-get install libmagic-dev libatlas-base-dev
```

**Comment by rhclayto** [comment]
I'm on Arch Linux & I had to install openblas-lapack 0.2.20-1 from the AUR user repository: https://aur.archlinux.org/packages/openblas-lapack/

**Comment by alexdufetel** [comment]
I'm having issues trying to install Snowboy on a RPi (raspbian) using node 8.4.0 and 8.6.0 (tried both):
- I installed swig, sox and portaudio
- I installed libmagic-dev and libatlas-base
- I tried running with npm install as admin or as a regular user
- I tried in two different project folders, including a blank one
- I am running npm install --save snowboy

Any help would be much  appreciated! 


node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
module.js:491
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.41-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/Magic/snowboy/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/Magic/snowboy/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm"
gyp ERR! cwd /home/pi/Magic/snowboy/node_modules/snowboy
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/Magic/snowboy/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/Magic/snowboy/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/Magic/snowboy/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.9.41-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/Magic/snowboy/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/Magic/snowboy/node_modules/snowboy
node-pre-gyp ERR! node -v v8.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/Magic/snowboy/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/Magic/snowboy/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm' (1)
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/Magic/snowboy/package.json'
npm WARN snowboy No description
npm WARN snowboy No repository field.
npm WARN snowboy No README data
npm WARN snowboy No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-10-24T02_43_37_224Z-debug.log

**Comment by alexdufetel** [comment]
installing nan module fixed this. Also, terrible name for a module...

**Comment by sintetico82** [comment]
I have the same issue. I try to install nan module but i still have the message:
node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v57-linux-arm.tar.gz 

I am on Rasberry pi 3, with node version 8.9.1

**Comment by chenguoguo** [comment]
We do not have support for v57 yet

**Comment by icripps** [comment]
having same issue, has this been solved yet?

**Comment by evancohen** [comment]
@icripps this is fixed in #537, we're just waiting for it to get merged.

**Comment by icripps** [comment]
@evancohen i am on node 11, idk if the fix will work on it

**Comment by jrobinson041** [comment]
Tried every solution listed here, installed every dependency listed in the README, still getting the 403 error alexdufetel was getting. Is Raspbian 9 supported?

Using:
Raspbian GNU/Linux 9 (stretch)
Node v10.16.0
npm 6.9.0




npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the
best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> snowboy@1.3.1 install /home/pi/jarvis/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/jarvis/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
make: Entering directory '/home/pi/jarvis/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
rm: cannot remove './Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw':
No such file or directory
snowboy.target.mk:107: recipe for target 'Release/obj.target/snowboy/swig/Node/snowboy.o'
failed
make: *** [Release/obj.target/snowboy/swig/Node/snowboy.o] Error 1
make: Leaving directory '/home/pi/jarvis/node_modules/snowboy/build'
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.42-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/jarvis/node_modules/snowboy
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/jarvis/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.42-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/jarvis/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/jarvis/node_modules/snowboy
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
  COPY Release/snowboy.nodeall: info lifecycle snowboy@1.3.1~install: Failed to exec inst
  COPY /home/pi/jarvis/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/jarvis/node_modules/snowboy/build'
npm WARN raspberrypi1@1.0.0 No description
npm WARN raspberrypi1@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-05-30T23_19_29_574Z-debug.log

**Comment by evancohen** [comment]
@jrobinson041 you also installed nan globally?
```
npm install -g nan
```

**Comment by evancohen** [comment]
The 403 isn't *really* an issue. That just means it needs to build locally because it can't find a precompiled binary. It's failing on build with a pretty nondescript error. Your error is definitely different from Alex's, it isn't related to nan being a missing package. The build error might be because we haven't updated nan/node-pre-gyp in a while, but like I said, it's too hard to tell from this. Can you use the `--verbose` flag when installing to see if that gives anything more helpful?

**Comment by jrobinson041** [comment]
https://pastebin.com/UKPLu1dr

**Comment by jrobinson041** [comment]
I looked through the more detailed errors that I pasted above and I believe this was able to solve my problem:
https://stackoverflow.com/questions/38323880/error-eacces-permission-denied

I haven't confirmed everything works as it should but I didn't get any errors after the 403.
I'll report back if I confirm everything is working properly.

**Comment by evancohen** [comment]
So it's not ideal, but you could try running the install with sudo - that may fix the permissions issues. Do you have a multi user setup on your pi?

**Comment by jrobinson041** [comment]
I have a single (not root) user on my Pi that I use. Running as sudo I believe changed the errors I was getting into the first pastebin I posted (EACCES: permission denied), but now I have the less descript error in the second pastebin I posted.

  g++ '-DNODE_GYP_MODULE_NAME=snowboy' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.node-gyp/10.16.0/include/node -I/home/pi/.node-gyp/10.16.0/src -I/home/pi/.node-gyp/10.16.0/deps/openssl/config -I/home/pi/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/pi/.node-gyp/10.16.0/deps/uv/include -I/home/pi/.node-gyp/10.16.0/deps/zlib -I/home/pi/.node-gyp/10.16.0/deps/v8/include -I../../nan -I/home/pi/jarvis/node_modules/snowboy/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -std=c++11 -fexceptions -Wall -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -fno-omit-frame-pointer -fno-rtti -std=gnu++1y -MMD -MF ./Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw   -c -o Release/obj.target/snowboy/swig/Node/snowboy.o ../swig/Node/snowboy.cc
rm: cannot remove './Release/.deps/Release/obj.target/snowboy/swig/Node/snowboy.o.d.raw': No such file or directory
snowboy.target.mk:107: recipe for target 'Release/obj.target/snowboy/swig/Node/snowboy.o' failed
make: *** [Release/obj.target/snowboy/swig/Node/snowboy.o] Error 1
make: Leaving directory '/home/pi/jarvis/node_modules/snowboy/build'
  g++ -shared -pthread -rdynamic -Wl,--no-as-needed  -Wl,-soname=snowboy.node -o Release/obj.target/snowboy.node -Wl,--start-group
Release/obj.target/snowboy/swig/Node/snowboy.o -Wl,--end-group -lcblas /home/pi/jarvis/node_modules/snowboy/lib/rpi/libsnowboy-detect.a
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

This is where the build seems to break now, could it be an issue with swig? 
I installed swig following this:
https://github.com/swig/swig/wiki/Getting-Started

**Comment by jrobinson041** [comment]
I was able to fix all of the above just by downgrading to Node 8.16.0

Unfortunately looks like Node 8 won't be in maintenance for much longer :(

**Comment by evancohen** [comment]
@jrobinson041 Can you try using `snowboy@1.2.0` when you run the install? Maybe the bindings changed in `1.3.x` and that's the issue? (total guess here)

**Comment by evancohen** [comment]
So the good news is that means your error just means nan or gyp needs to be upgraded, which there is already a PR out for #537. The slightly less good news is that PR has been sitting waiting to get merged for a while and I'm not sure when (or if?) the maintainers will get to it.

I'll see if I can find a good work-around.

**Comment by evancohen** [comment]
@jrobinson041 I've put together a really easy way to install snowboy, which uses the latest version of the library (1.3.1) and is compatible with Node 6-12 with precompiled binaries for OSX, x86, and ARM (Pi). All you've got to do is run:
```
npm install snoyboy@sonus
```

**Comment by misk0** [comment]
> 
You have typo,  command shoud be:

```
npm install snowboy@sonus
```

> 
> @jrobinson041 I've put together a really easy way to install snowboy, which uses the latest version of the library (1.3.1) and is compatible with Node 6-12 with precompiled binaries for OSX, x86, and ARM (Pi). All you've got to do is run:
> 
> ```
> npm install snoyboy@sonus
> ```

**Comment by evancohen** [comment]
@misk0 thanks for the catch!
