### ISSUE TITLE
Unable to Test/Download Any Voice Models (Save and Download are Greyed Out)

### ISSUE THREAD

**Issue by grimsikk** [Kitt-AI/snowboy#656]
Please fix this issue, it's clearly a big problem since everyone else is posting about it too.

I cannot get past the "Test the Model" step for getting a hotword from your website. It clearly shows a waveform and can hear me saying the hotword, yet the Save and Save and Download buttons remain greyed out no matter what I do. I'm using the proper wav files, my mic is high quality and I'm in a dead silent room, yet your website is broken and will not let anyone save and download the models!!

Please fix this, I've been trying to just have a custom wake word for my phones google assistant for like 2 years now, it shouldn't be this hard to do.

**Comment by nairolf27** [comment]
Same issue

**Comment by GODOFHOU** [comment]
The same problem, press F12 in the browser, I see some errors on the website

**Comment by luvwinnie** [comment]
it seems like the websocket server down?
<img width="608" alt="Screen Shot 2020-05-05 at 13 01 23" src="https://user-images.githubusercontent.com/13714992/81034012-a45b2580-8ed0-11ea-98b5-bc22d2fdbb90.png">

**Comment by RasyiidWho** [comment]
bump

**Comment by chadananda** [comment]
Annoying:

Console error:
  Firefox can’t establish a connection to the server at wss://snowboy-wss.kitt.ai/vad.

Same in Chrome

**Comment by enpeizhao** [comment]
I sovled this problem by use their [RESTful API Calls](http://docs.kitt.ai/snowboy/#restful-api), it works!

**Comment by nairolf27** [comment]
@enpeizhao It works perfectly for me! The handling is rather simple (more complicated than the website anyway ^^). I was able to create my hotword in 3 minutes on my raspberry.

**Comment by Dalkei** [comment]
It seems this issue has been resolved.

**Comment by lajos64** [comment]
For me it seems the problem still exists, today.
From a couple of days I'm unable to perform (and download) a test. Exactly on the first post on the top. Some days ago I created some hotwords on a Win 10 Laptop with Chrome, without any trouble. I was able to test and download the hotwords just created, on the laptop.... and so on...
But from a couple of days, as I press the "Run test" button in the website, it immediately stops.
I have no time to speak, for verify the hotword. So I can't download nothing.
I tried with Chrome (some days ago working!) and Firefox too. But the same behavior!
Notice: Chrome appears to be upgraded on May 27. Is this meaningful, or meaningless?

Thank for any suggestion

**Comment by carlobono** [comment]
> For me it seems the problem still exists, today.

Same thing for me too. Same behavior: hotword testing stops a bit quiker than expected (almost instantly), buttons greyed out.
Tested with chrome and firefox.

All the best
cb

**Comment by lajos64** [comment]
Perhaps the attachments confirm the problem. The errors appear in the debug window immediately after clicking the first of the three microphones, even before starting to speak.

regards

<img width="960" alt="New_Hotword_err" src="https://user-images.githubusercontent.com/66277640/83669532-02fbe800-a5d2-11ea-8248-9e74c9a3f908.png">
[snowboy.kitt.ai-1591203016672.log](https://github.com/Kitt-AI/snowboy/files/4725133/snowboy.kitt.ai-1591203016672.log)

**Comment by chenguoguo** [comment]
The detecting issue has been resolved. The screenshot was for a different
issue though.

Guoguo

**Comment by carlobono** [comment]
Many thanks!

**Comment by lajos64** [comment]
Thanks very much
Regards
